package com.dmjm.model;
// Generated 10/02/2025 02:20:26 PM by Hibernate Tools 4.3.1



/**
 * FolioImportacion generated by hbm2java
 */
public class FolioImportacion  implements java.io.Serializable {


     private int idFolio;
     private Long folio;

    public FolioImportacion() {
    }

	
    public FolioImportacion(int idFolio) {
        this.idFolio = idFolio;
    }
    public FolioImportacion(int idFolio, Long folio) {
       this.idFolio = idFolio;
       this.folio = folio;
    }
   
    public int getIdFolio() {
        return this.idFolio;
    }
    
    public void setIdFolio(int idFolio) {
        this.idFolio = idFolio;
    }
    public Long getFolio() {
        return this.folio;
    }
    
    public void setFolio(Long folio) {
        this.folio = folio;
    }




}


