package com.dmjm.model;
// Generated 19/11/2024 11:24:22 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SaldoFactura generated by hbm2java
 */
public class SaldoFactura  implements java.io.Serializable {


     private int idSaldo;
     private String factura;
     private BigDecimal nuevoSaldo;

    public SaldoFactura() {
    }

	
    public SaldoFactura(int idSaldo) {
        this.idSaldo = idSaldo;
    }
    public SaldoFactura(int idSaldo, String factura, BigDecimal nuevoSaldo) {
       this.idSaldo = idSaldo;
       this.factura = factura;
       this.nuevoSaldo = nuevoSaldo;
    }
   
    public int getIdSaldo() {
        return this.idSaldo;
    }
    
    public void setIdSaldo(int idSaldo) {
        this.idSaldo = idSaldo;
    }
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }
    public BigDecimal getNuevoSaldo() {
        return this.nuevoSaldo;
    }
    
    public void setNuevoSaldo(BigDecimal nuevoSaldo) {
        this.nuevoSaldo = nuevoSaldo;
    }




}


